// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1) {
  return window['go']['app']['App']['AddDirectory'](arg1);
}

export function EnsureExportRelDir(arg1, arg2) {
  return window['go']['app']['App']['EnsureExportRelDir'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function ListGitCommits(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListGitCommits'](arg1, arg2, arg3);
}

export function ListGitTableFiles(arg1, arg2) {
  return window['go']['app']['App']['ListGitTableFiles'](arg1, arg2);
}

export function MoveDirectory(arg1, arg2) {
  return window['go']['app']['App']['MoveDirectory'](arg1, arg2);
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function PrepareExportDirectory(arg1) {
  return window['go']['app']['App']['PrepareExportDirectory'](arg1);
}

export function ReadGitTableFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ReadGitTableFile'](arg1, arg2, arg3);
}

export function ReadTableFile(arg1) {
  return window['go']['app']['App']['ReadTableFile'](arg1);
}

export function RemoveDirectory(arg1) {
  return window['go']['app']['App']['RemoveDirectory'](arg1);
}

export function ResolveGitRepo(arg1) {
  return window['go']['app']['App']['ResolveGitRepo'](arg1);
}

export function ScanActiveDirectory() {
  return window['go']['app']['App']['ScanActiveDirectory']();
}

export function SetActiveDirectory(arg1) {
  return window['go']['app']['App']['SetActiveDirectory'](arg1);
}

export function ShowInExplorer(arg1) {
  return window['go']['app']['App']['ShowInExplorer'](arg1);
}

export function WriteTableFile(arg1, arg2) {
  return window['go']['app']['App']['WriteTableFile'](arg1, arg2);
}
