// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDirectory(arg1) {
  return window['go']['app']['App']['AddDirectory'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function PickDirectory() {
  return window['go']['app']['App']['PickDirectory']();
}

export function ReadTableFile(arg1) {
  return window['go']['app']['App']['ReadTableFile'](arg1);
}

export function RemoveDirectory(arg1) {
  return window['go']['app']['App']['RemoveDirectory'](arg1);
}

export function ScanActiveDirectory() {
  return window['go']['app']['App']['ScanActiveDirectory']();
}

export function SetActiveDirectory(arg1) {
  return window['go']['app']['App']['SetActiveDirectory'](arg1);
}

export function WriteTableFile(arg1, arg2) {
  return window['go']['app']['App']['WriteTableFile'](arg1, arg2);
}
