// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {scanner} from '../models';

export function AddDirectory(arg1:string):Promise<config.Settings>;

export function EnsureExportRelDir(arg1:string,arg2:string):Promise<void>;

export function GetSettings():Promise<config.Settings>;

export function PickDirectory():Promise<string>;

export function PrepareExportDirectory(arg1:string):Promise<string>;

export function ReadTableFile(arg1:string):Promise<string>;

export function RemoveDirectory(arg1:string):Promise<config.Settings>;

export function ScanActiveDirectory():Promise<scanner.TreeNode>;

export function SetActiveDirectory(arg1:string):Promise<config.Settings>;

export function ShowInExplorer(arg1:string):Promise<void>;

export function WriteTableFile(arg1:string,arg2:string):Promise<void>;
